name: Event Details

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  print-event-details:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Print event details
      run: |
        echo "Event Name: ${{ github.event_name }}"
        echo "Event Action: ${{ github.event.action }}"
        echo "Repository: ${{ github.repository }}"
        echo "Actor: ${{ github.actor }}"
        echo "Ref: ${{ github.ref }}"
        echo "SHA: ${{ github.sha }}"